export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;

export const CARD_ASSIGN_STATUS = {
  ASSIGNING: 'ASSIGNING',
  ASSIGNED: 'ASSIGNED',
} as const;

export const CARD_DELIVER_STATUS = {
  NOT_DELIVERED: 'NOT_DELIVERED',
  DELIVERED: 'DELIVERED',
} as const;

export const BOOKING_STATUS = {
  NEW: 'NEW',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAIL: "PAYMENT_FAIL",
  CARD_SUCCESS: "CARD_SUCCESS",
  FINISH: "FINISH"
} as const